spring:
  application:
    name: hrm

  datasource:
    username: postgres
    password: 18701028
    url: jdbc:postgresql://localhost:5432/hrmdb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: com.atpi.config.CustomPostgresDialect

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.touhed: DEBUG
  file:
    path: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#jwt:
#  access-token-secret: ${ACCESS_TOKEN_SECRET}
#  refresh-token-secret: ${REFRESH_TOKEN_SECRET}
#  expiration: ${ACCESS_TOKEN_EXPIRATION}
#  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    path: /atpi-api-docs